platformName=Android
automationName=UiAutomator2
deviceName=Android Emulator
appPath=../app/build/outputs/apk/debug/app-debug.apk
appPackage=com.saveetha.aipulpcapping
appActivity=.MainActivity
appiumServerUrl=http://127.0.0.1:4723
implicitWait=10
explicitWait=20
