package com.saveetha.aipulpcapping.utils

import android.content.Context
import android.os.Environment
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.TextAlignment
import com.saveetha.aipulpcapping.model.Analysis
import com.saveetha.aipulpcapping.model.Patient
import java.io.File
import java.io.FileOutputStream

object PdfGenerator {
    fun generatePatientReport(context: Context, patient: Patient, analysis: Analysis): File? {
        val fileName = "Report_${patient.id}_${System.currentTimeMillis()}.pdf"
        val path = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)
        val file = File(path, fileName)

        try {
            val writer = PdfWriter(FileOutputStream(file))
            val pdf = PdfDocument(writer)
            val document = Document(pdf)

            // Header
            document.add(Paragraph("AI BASED PULP CAPPING - CLINICAL REPORT")
                .setBold().setFontSize(18f).setTextAlignment(TextAlignment.CENTER))
            
            document.add(Paragraph("Generated on: ${analysis.date} at ${analysis.time}")
                .setFontSize(10f).setTextAlignment(TextAlignment.RIGHT))

            // Patient Info Section
            document.add(Paragraph("\nPATIENT DETAILS").setBold().setUnderline())
            document.add(Paragraph("Name: ${patient.name}"))
            document.add(Paragraph("ID: ${patient.id}"))
            document.add(Paragraph("Age: ${patient.age} | Gender: ${patient.gender}"))
            document.add(Paragraph("Medical History: ${patient.history}"))

            // AI Analysis Section
            document.add(Paragraph("\nDIAGNOSTIC ANALYSIS").setBold().setUnderline())
            val table = Table(floatArrayOf(1f, 1f))
            table.useAllAvailableWidth()
            
            table.addCell("Risk Assessment")
            table.addCell(analysis.result)
            
            table.addCell("Measured RDT")
            table.addCell(analysis.rdtValue)
            
            table.addCell("AI Confidence")
            table.addCell(analysis.confidence)
            
            table.addCell("Recommended Material")
            table.addCell(analysis.material)

            document.add(table)

            document.add(Paragraph("\nCLINICAL RECOMMENDATIONS").setBold())
            document.add(Paragraph(analysis.recommendations))

            // Footer
            document.add(Paragraph("\n\n* This report is generated by AI assistant and should be verified by a licensed clinician.")
                .setFontSize(8f).setItalic())

            document.close()
            return file
        } catch (e: Exception) {
            e.printStackTrace()
            return null
        }
    }
}
